import type {
  AssessmentQuestion,
  AxisKey,
  ChecklistItem,
  CommitmentLevel,
  CommitmentQuestion,
  LearningItem,
  PhaseMeta,
  RoadmapByCommitment,
  StoreProfile,
  StumblingPoint,
  SupportItem,
  TaskItem,
} from './types'

// 教材カテゴリの表示名（導入ステージ別）
export const learningCategoryLabels: Record<string, string> = {
  phase0: '検討・経営判断',
  phase1: '方針・体制づくり',
  phase2: '受入準備',
  phase3: '初回受入・実務',
  phase4: '安定運用・標準化',
  phase5: '夜間・緊急対応',
  template: 'テンプレート',
  'knowledge-system': '在宅の仕組み',
  'knowledge-kasan': '加算・算定',
  'knowledge-materials': '医療材料',
  'skill-aseptic': '無菌調剤',
  'skill-pump': 'ポンプ操作',
  'skill-compatibility': '配合変化',
  'skill-narcotic': '麻薬管理',
}

export const storeProfile: StoreProfile = {
  name: '',
  owner: '',
  manager: '',
  area: '',
  startGoal: '在宅の初回受入を、店舗内で迷わず回せる状態にする',
  nextMeeting: '',
  readinessLabel: '',
  firstActionTime: '5〜10分',
}

// 本気度診断
export const commitmentQuestions: CommitmentQuestion[] = [
  {
    id: 'commitment-goal',
    question: '在宅をどのくらいの規模で考えていますか？',
    options: [
      { label: '地域支援体制加算を取得できればOK', level: 'basic' },
      { label: '在宅を中規模（10-30件程度）でやっていきたい', level: 'moderate' },
      { label: '本格的に在宅事業として展開したい（30件以上）', level: 'full' },
    ],
  },
  {
    id: 'commitment-night',
    question: '夜間・緊急対応についてどう考えていますか？',
    options: [
      { label: '日中対応のみで十分', level: 'basic' },
      { label: '将来的には検討したい', level: 'moderate' },
      { label: '24時間365日対応を目指す', level: 'full' },
    ],
  },
]

// 6軸診断
export const assessmentQuestions: AssessmentQuestion[] = [
  {
    id: 'vision',
    category: '経営・方針',
    question: 'オーナー（経営者）は在宅医療に取り組む意思を持っていますか？',
    help: '経営者が在宅について理解していない状態で始めると、体制が整わず紹介が途絶えるリスクがあります。',
    weight: 3,
    options: [
      { label: 'まだ検討中・曖昧', score: 1.5, detail: '経営判断として在宅に取り組むか未決定の状態です。' },
      { label: '方針は決定済み', score: 3.5, detail: '在宅に取り組む方針は決まっているが、現場への周知が不十分な可能性があります。' },
      { label: 'スタッフにも周知・共有済み', score: 5.0, detail: '在宅の必要性、やらないとどうなるかまでスタッフに説明できている状態です。' },
    ],
  },
  {
    id: 'role',
    category: '体制・役割分担',
    question: '現場が在宅に取り組む姿勢はありますか？新規を断らない体制ができていますか？',
    help: '現場の取り組み姿勢が整わないまま営業を始めると、対応不備につながります。',
    weight: 3,
    options: [
      { label: '姿勢がまだ固まっていない', score: 1.5, detail: 'スタッフの在宅への理解や意欲がまだ低い状態です。' },
      { label: '一部のスタッフは前向き', score: 3.0, detail: '在宅に意欲的なスタッフがいるが、全体としての体制はこれからです。' },
      { label: '断らない体制ができている', score: 5.0, detail: '新規依頼を受けても対応できる役割分担と姿勢が整っています。' },
    ],
  },
  {
    id: 'equipment',
    category: '設備',
    question: 'クリーンベンチや各種ポンプ類の設備はありますか？',
    help: '無菌調剤や各種ポンプ対応ができると、受けられる患者の幅が広がります。',
    weight: 1,
    options: [
      { label: 'どちらもない', score: 2.0, detail: '基本的な在宅は可能ですが、対応範囲が限られます。' },
      { label: 'クリーンベンチのみ', score: 3.5, detail: '無菌調剤対応可能。ポンプ対応は今後の課題です。' },
      { label: '両方揃っている', score: 5.0, detail: '無菌調剤・ポンプ対応ともに可能で、幅広い患者を受けられます。' },
    ],
  },
  {
    id: 'education',
    category: '教育・標準化',
    question: 'スタッフへの在宅教育（なぜ必要か、やらないとどうなるか）は進んでいますか？',
    help: '在宅の必要性を理解し、受入体制を作りながら教育を進める必要があります。',
    weight: 2,
    options: [
      { label: 'まだ始めていない', score: 1.5, detail: '在宅の必要性・やり方の教育がこれからの状態です。' },
      { label: '一部のスタッフは学習中', score: 3.0, detail: '教育を始めているが、全員への展開はこれからです。' },
      { label: '基本教育完了', score: 4.5, detail: '必要な知識・スキルの基本教育が完了しています。' },
    ],
  },
  {
    id: 'operations',
    category: '受入準備・運用',
    question: '初回患者を受け入れるための準備（受入条件表、フロー、チェックリスト）は整っていますか？',
    help: '体制が整っていない状態で受けると対応ができず、紹介が途絶えるリスクがあります。',
    weight: 2,
    options: [
      { label: 'まだ口頭中心', score: 2.0, detail: '判断基準が頭の中にあり、引き継ぎや共有が難しい状態です。' },
      { label: '作成中', score: 3.0, detail: 'あと一歩で運用に乗せられる段階です。' },
      { label: '実務導線まで整っている', score: 4.5, detail: '複数人で再現できる形になっています。' },
    ],
  },
  {
    id: 'night',
    category: '夜間・緊急対応準備',
    question: '夜間帯に引き継ぐための患者情報入力体制はありますか？',
    help: '24時間365日対応は患者紹介を増やすうえで重要です。ただしすぐに始める必要はありません。',
    weight: 3,
    options: [
      { label: 'まだ考えていない', score: 1.0, detail: '今は昼間の受入準備を優先する段階です。' },
      { label: '検討・準備中', score: 2.5, detail: '夜間対応の必要性は認識しており、準備を進めている状態です。' },
      { label: '患者情報入力体制あり', score: 4.0, detail: '夜間帯への引き継ぎができる情報管理体制が整っています。' },
    ],
  },
]

export const defaultAnswers: Record<AxisKey, number> = {
  vision: 1,
  role: 1,
  equipment: 0,
  education: 0,
  operations: 1,
  night: 0,
}

export const defaultCommitmentLevel: CommitmentLevel = 'moderate'

// 本気度別ロードマップ
export const roadmapByCommitment: RoadmapByCommitment[] = [
  {
    level: 'basic',
    label: '地域支援体制加算取得コース',
    description: '地域支援体制加算の要件を満たすことを目標にした導入',
    targetPhase: 3,
    features: [
      '基本的な在宅対応体制の構築',
      '必要最低限の教育',
      '日中対応のみ',
    ],
    nightSupport: false,
  },
  {
    level: 'moderate',
    label: '中規模在宅コース',
    description: '在宅患者10-30件程度を安定運用することを目標にした導入',
    targetPhase: 4,
    features: [
      '標準的な在宅対応体制',
      '段階的な教育プログラム',
      '将来的な夜間対応を見据えた準備',
    ],
    nightSupport: false,
  },
  {
    level: 'full',
    label: '本格在宅事業コース',
    description: '30件以上の在宅患者を抱え、24時間365日対応を目指す',
    targetPhase: 5,
    features: [
      '断らない体制の構築',
      '包括的な教育と標準化',
      '夜間・緊急対応体制',
      '設備投資（クリーンベンチ、ポンプ）',
    ],
    nightSupport: true,
  },
]

// タスク（本気度別）
export const tasks: TaskItem[] = [
  {
    id: 'task-owner-decision',
    title: 'オーナーが在宅に取り組む方針を決定・表明する',
    owner: 'オーナー',
    due: '最初に',
    status: '未着手',
    note: 'スタッフに在宅の必要性とやらないとどうなるかを説明します。',
    review: '経営者の意思決定がすべての起点です。',
    deliverable: '方針決定メモ',
    relatedContentId: 'learning-why-zaitaku',
    nextAction: 'スタッフミーティングで方針を共有する。',
    successMetric: '全スタッフが在宅に取り組む理由を説明できる状態',
    commitmentLevels: ['basic', 'moderate', 'full'],
  },
  {
    id: 'task-staff-mindset',
    title: 'スタッフへの在宅教育（マインドセット）',
    owner: '管理薬剤師',
    due: '1週目',
    status: '未着手',
    note: '在宅がなぜ必要か、やらないとどうなるかを現場に周知します。',
    review: '立ち上げ部分は伴走支援が必要です。薬剤師のマインドセット変革が鍵。',
    deliverable: '教育実施記録',
    relatedContentId: 'learning-mindset',
    nextAction: '在宅の必要性を説明する勉強会を開催する。',
    successMetric: '現場が在宅に前向きな姿勢を持てている状態',
    commitmentLevels: ['basic', 'moderate', 'full'],
  },
  {
    id: 'task-role-assignment',
    title: '役割分担表の作成',
    owner: '管理薬剤師',
    due: '1週目',
    status: '未着手',
    note: '責任者・主担当・相談先・不在時の代替担当を整理します。',
    review: '役割分担の型は標準化しやすい部分です。',
    deliverable: '役割分担表',
    relatedContentId: 'learning-role-template',
    nextAction: '役割分担表テンプレートを埋める。',
    successMetric: '誰が休みでも判断と相談が止まらない状態',
    commitmentLevels: ['basic', 'moderate', 'full'],
  },
  {
    id: 'task-acceptance',
    title: '受入条件表をこの薬局向けに埋める',
    owner: '管理薬剤師',
    due: '2週目',
    status: '未着手',
    note: '施設系・個人宅・緊急時の3ケースで受入条件を分けて整理します。',
    review: '曖昧語を減らし、「誰が判断するか」を各欄に入れると使いやすくなります。',
    deliverable: '受入条件表 v1',
    relatedContentId: 'learning-acceptance-template',
    nextAction: 'まず3ケースの受入可否と相談先を入力する。',
    successMetric: '責任者以外が見ても、受入判断と相談先が止まらない状態',
    commitmentLevels: ['basic', 'moderate', 'full'],
  },
  {
    id: 'task-flow',
    title: '初回患者受入フローを1枚にする',
    owner: '事務',
    due: '2週目',
    status: '未着手',
    note: '問い合わせから初回訪問後の共有まで、1枚で追えるように整理します。',
    review: '医師連携と家族説明の受け渡しポイントを追記すると現場で使いやすくなります。',
    deliverable: '初回受入フロー図',
    relatedContentId: 'learning-flow-document',
    nextAction: '薬局内 / 医師連携 / 家族説明の3レーンで下書きを作る。',
    successMetric: '初回受入時に「次に誰が動くか」で止まらない状態',
    commitmentLevels: ['basic', 'moderate', 'full'],
  },
  {
    id: 'task-checklist',
    title: '初回受入前チェックリストの確認',
    owner: '管理薬剤師',
    due: '3週目',
    status: '未着手',
    note: '受入準備が整っているかを最終確認します。',
    review: 'このチェックリストを通過したら営業・獲得に動けます。',
    deliverable: 'チェック完了記録',
    relatedContentId: 'learning-checklist',
    nextAction: 'チェックリストの各項目を確認する。',
    successMetric: '初回受入可能と判断できる状態',
    commitmentLevels: ['basic', 'moderate', 'full'],
  },
  {
    id: 'task-skill-cleanroom',
    title: 'クリーンベンチ操作の習得',
    owner: '薬剤師',
    due: '2週目',
    status: '未着手',
    note: '無菌調剤の基本手技を習得します。',
    review: '現場でつまずきやすいポイントです。動画を見て練習してください。',
    deliverable: '手技確認記録',
    relatedContentId: 'learning-cleanroom-video',
    nextAction: '動画を視聴し、実際に練習する。',
    successMetric: 'クリーンベンチを使った無菌調剤ができる状態',
    commitmentLevels: ['moderate', 'full'],
  },
  {
    id: 'task-skill-pump',
    title: 'ポンプ類の取り扱い習得',
    owner: '薬剤師',
    due: '2週目',
    status: '未着手',
    note: '各種ポンプの操作方法を習得します。',
    review: '現場でつまずきやすいポイントです。配合変化にも注意。',
    deliverable: '手技確認記録',
    relatedContentId: 'learning-pump-video',
    nextAction: '動画を視聴し、実際に練習する。',
    successMetric: 'ポンプの設定・トラブル対応ができる状態',
    commitmentLevels: ['moderate', 'full'],
  },
  {
    id: 'task-night-policy',
    title: '夜間方針の整理',
    owner: 'オーナー',
    due: '受入後',
    status: '未着手',
    note: '夜間対応をどう進めるかの方針を整理します。',
    review: '10-20人抱えたタイミング、または初回導入後に検討してください。',
    deliverable: '夜間方針メモ',
    relatedContentId: 'learning-night-policy',
    nextAction: '夜間対応の必要性とリスクを整理する。',
    successMetric: '夜間対応するかどうかの判断ができる状態',
    commitmentLevels: ['full'],
  },
  {
    id: 'task-night-info',
    title: '夜間引き継ぎ用の患者情報入力体制構築',
    owner: '管理薬剤師',
    due: '受入後',
    status: '未着手',
    note: '夜間帯に引き継ぐための患者情報入力フローを整備します。',
    review: '夜間支援につなぐ前の最低条件です。',
    deliverable: '患者情報入力フロー',
    relatedContentId: 'learning-night-info',
    nextAction: '患者情報の記録フォーマットを整備する。',
    successMetric: '夜間帯への引き継ぎが可能な状態',
    commitmentLevels: ['full'],
  },
]

// 教材
export const learningItems: LearningItem[] = [
  {
    id: 'learning-why-zaitaku',
    title: '在宅はなぜ必要か、やらないとどうなるか',
    type: '資料',
    target: 'オーナー / 管理薬剤師',
    description: '在宅に取り組む理由と、取り組まないリスクを整理した資料です。',
    duration: '10分',
    outcome: '在宅の必要性を説明できる',
    linkedTaskId: 'task-owner-decision',
    previewTitle: '資料の内容',
    previewMeta: '経営判断の起点',
    previewLines: ['地域における薬局の役割変化', '在宅をやらない場合のリスク', '取り組みの段階的ステップ'],
    ctaLabel: '資料を見る',
    category: 'phase0',
    commitmentLevels: ['basic', 'moderate', 'full'],
  },
  {
    id: 'learning-mindset',
    title: 'スタッフの在宅マインドセット構築',
    type: '資料',
    target: '管理薬剤師 / スタッフ',
    description: '現場スタッフが在宅に前向きになるための勉強会資料です。',
    duration: '15分',
    outcome: 'スタッフが在宅に前向きになる',
    linkedTaskId: 'task-staff-mindset',
    previewTitle: '資料の内容',
    previewMeta: '勉強会用スライド',
    previewLines: ['在宅の現場ではこう変わる', '不安なことへの回答集', '先輩薬局の声'],
    ctaLabel: '資料を見る',
    category: 'phase1',
    commitmentLevels: ['basic', 'moderate', 'full'],
  },
  {
    id: 'learning-zaitaku-system',
    title: '在宅の仕組み（ケアマネ、クリニックとの関係）',
    type: '資料',
    target: '全スタッフ',
    description: '在宅医療の関係者と薬局の役割を整理した資料です。',
    duration: '15分',
    outcome: '在宅の全体像を理解できる',
    linkedTaskId: 'task-staff-mindset',
    previewTitle: '資料の内容',
    previewMeta: '基礎知識',
    previewLines: ['医師・ケアマネ・訪看との関係', '薬局の役割と責任範囲', '情報共有のポイント'],
    ctaLabel: '資料を見る',
    category: 'knowledge-system',
    commitmentLevels: ['basic', 'moderate', 'full'],
  },
  {
    id: 'learning-role-template',
    title: '役割分担表テンプレート',
    type: 'テンプレ',
    target: '管理薬剤師',
    description: '責任者・主担当・代替担当を整理するためのテンプレートです。',
    duration: '10分',
    outcome: '役割分担が明確になる',
    linkedTaskId: 'task-role-assignment',
    previewTitle: 'テンプレの項目',
    previewMeta: '',
    previewLines: ['責任者・連絡先', '主担当・副担当', '不在時の代替フロー'],
    ctaLabel: 'テンプレをダウンロード',
    category: 'template',
    commitmentLevels: ['basic', 'moderate', 'full'],
    downloadUrl: '/templates/role-assignment-template.pdf',
  },
  {
    id: 'learning-acceptance-template',
    title: '受入条件表テンプレート',
    type: 'テンプレ',
    target: '管理薬剤師',
    description: '患者受入判断を、薬局ごとに落とし込むための雛形です。',
    duration: '15分',
    outcome: '受入可否の判断基準がそろう',
    linkedTaskId: 'task-acceptance',
    previewTitle: 'テンプレに入っている項目',
    previewMeta: 'A4 1枚で使う想定',
    previewLines: ['受入可否の判断欄', '迷いやすいケースの補足欄', '相談先・判断者の記入欄'],
    ctaLabel: 'テンプレをダウンロード',
    category: 'template',
    commitmentLevels: ['basic', 'moderate', 'full'],
    downloadUrl: '/templates/acceptance-criteria-template.pdf',
  },
  {
    id: 'learning-flow-document',
    title: '初回受入フローたたき台',
    type: '資料',
    target: '事務 / 現場メンバー',
    description: '問い合わせから初回訪問後の共有までを、1枚で見えるようにするための資料です。',
    duration: '10分',
    outcome: '受入フローを店舗内で説明できる',
    linkedTaskId: 'task-flow',
    previewTitle: '資料で整理する場面',
    previewMeta: '会議用の下書きに最適',
    previewLines: ['問い合わせ受付', '医師・家族との連携', '初回訪問後の共有'],
    ctaLabel: '資料をダウンロード',
    category: 'phase2',
    commitmentLevels: ['basic', 'moderate', 'full'],
    downloadUrl: '/templates/first-acceptance-flow.pdf',
  },
  {
    id: 'learning-checklist',
    title: '初回受入前チェックリスト',
    type: 'チェックリスト',
    target: '管理薬剤師',
    description: '初回患者受入可能かどうかを確認するためのチェックリストです。',
    duration: '5分',
    outcome: '受入可否を判断できる',
    linkedTaskId: 'task-checklist',
    previewTitle: 'チェック項目',
    previewMeta: '最終確認用',
    previewLines: ['方針決定済み', '役割分担完了', '受入条件表作成済み', '基本教育完了'],
    ctaLabel: 'チェックリストをダウンロード',
    category: 'phase2',
    commitmentLevels: ['basic', 'moderate', 'full'],
    downloadUrl: '/templates/pre-acceptance-checklist.pdf',
  },
  {
    id: 'learning-equipment-list',
    title: '在宅をやる上での必要備品一覧',
    type: '資料',
    target: '管理薬剤師 / オーナー',
    description: '在宅対応に必要な備品とその優先度を整理した一覧です。',
    duration: '10分',
    outcome: '必要備品がわかる',
    linkedTaskId: 'task-acceptance',
    previewTitle: '備品カテゴリ',
    previewMeta: '投資判断の参考に',
    previewLines: ['必須備品', 'あれば便利な備品', 'クリーンベンチ・ポンプ等'],
    ctaLabel: '一覧をダウンロード',
    category: 'phase2',
    commitmentLevels: ['basic', 'moderate', 'full'],
    downloadUrl: '/templates/equipment-list.pdf',
  },
  {
    id: 'learning-cleanroom-video',
    title: 'クリーンベンチの手技、現場での対応',
    type: '動画',
    target: '薬剤師',
    description: '無菌調剤の基本手技を動画で解説します。',
    duration: '20分',
    outcome: 'クリーンベンチが使える',
    linkedTaskId: 'task-skill-cleanroom',
    previewTitle: '動画の内容',
    previewMeta: '',
    previewLines: ['手洗い・ガウンテクニック', '無菌操作の基本', 'よくあるミスと対策'],
    ctaLabel: '動画を見る',
    category: 'skill-aseptic',
    commitmentLevels: ['moderate', 'full'],
  },
  {
    id: 'learning-pump-video',
    title: 'ポンプ類の取り扱い方',
    type: '動画',
    target: '薬剤師',
    description: '各種ポンプの設定方法とトラブル対応を動画で解説します。',
    duration: '25分',
    outcome: 'ポンプの操作ができる',
    linkedTaskId: 'task-skill-pump',
    previewTitle: '動画の内容',
    previewMeta: '',
    previewLines: ['シリンジポンプの設定', '輸液ポンプの設定', 'アラーム対応'],
    ctaLabel: '動画を見る',
    category: 'skill-pump',
    commitmentLevels: ['moderate', 'full'],
  },
  {
    id: 'learning-compatibility',
    title: '点滴の配合変化・側管投与の注意点',
    type: '資料',
    target: '薬剤師',
    description: '配合変化や側管から投与して詰まるケースなど、現場で起きやすい問題を解説します。',
    duration: '15分',
    outcome: '配合変化リスクを判断できる',
    linkedTaskId: 'task-skill-pump',
    previewTitle: '資料の内容',
    previewMeta: '',
    previewLines: ['よくある配合禁忌', '側管投与の注意点', '詰まった時の対応'],
    ctaLabel: '資料を見る',
    category: 'skill-compatibility',
    commitmentLevels: ['moderate', 'full'],
  },
  {
    id: 'learning-kasan',
    title: '在宅の加算関係（算定OK/NG）',
    type: '資料',
    target: '薬剤師 / 事務',
    description: '在宅での加算について、何が算定できて何がダメなのかを整理した資料です。',
    duration: '20分',
    outcome: '加算の可否を判断できる',
    linkedTaskId: 'task-acceptance',
    previewTitle: '資料の内容',
    previewMeta: '',
    previewLines: ['在宅患者訪問薬剤管理指導料', '麻薬管理指導加算', '無菌製剤処理加算'],
    ctaLabel: '資料を見る',
    category: 'knowledge-kasan',
    commitmentLevels: ['basic', 'moderate', 'full'],
  },
  {
    id: 'learning-narcotic',
    title: '麻薬の換算（フェントスからの切り替え等）',
    type: '資料',
    target: '薬剤師',
    description: '麻薬の換算計算と切り替え時の注意点を解説します。',
    duration: '15分',
    outcome: '麻薬換算ができる',
    linkedTaskId: 'task-skill-cleanroom',
    previewTitle: '資料の内容',
    previewMeta: '',
    previewLines: ['オピオイド換算表', 'フェントス切り替えの注意', 'レスキュー量の計算'],
    ctaLabel: '資料を見る',
    category: 'skill-narcotic',
    commitmentLevels: ['moderate', 'full'],
  },
  {
    id: 'learning-materials',
    title: '医療材料の処方可否（院内/院外処方）',
    type: '資料',
    target: '薬剤師 / 事務',
    description: '医療材料が処方できるのかできないのか、院内処方と院外処方の違いを解説します。',
    duration: '10分',
    outcome: '医療材料の取り扱いがわかる',
    linkedTaskId: 'task-acceptance',
    previewTitle: '資料の内容',
    previewMeta: '',
    previewLines: ['院外処方できる材料', '院内処方のみの材料', '判断に迷うケース'],
    ctaLabel: '資料を見る',
    category: 'knowledge-materials',
    commitmentLevels: ['basic', 'moderate', 'full'],
  },
  {
    id: 'learning-night-policy',
    title: '夜間方針の整理手順',
    type: '資料',
    target: 'オーナー / 管理薬剤師',
    description: '夜間対応をどう進めるかを判断するための整理資料です。',
    duration: '10分',
    outcome: '夜間対応の判断ができる',
    linkedTaskId: 'task-night-policy',
    previewTitle: '資料の内容',
    previewMeta: '',
    previewLines: ['夜間対応のメリット・コスト', '対応しない場合のリスク', '段階的な導入方法'],
    ctaLabel: '資料を見る',
    category: 'phase5',
    commitmentLevels: ['full'],
  },
  {
    id: 'learning-night-info',
    title: '夜間引き継ぎ用の患者情報入力フロー',
    type: 'テンプレ',
    target: '管理薬剤師',
    description: '夜間帯への引き継ぎに必要な患者情報の記録方法を整理したテンプレートです。',
    duration: '10分',
    outcome: '夜間引き継ぎができる',
    linkedTaskId: 'task-night-info',
    previewTitle: 'テンプレの内容',
    previewMeta: '',
    previewLines: ['必須記録項目', '記録タイミング', '引き継ぎフォーマット'],
    ctaLabel: 'テンプレを見る',
    category: 'template',
    commitmentLevels: ['full'],
  },
]

// つまずきポイント一覧
export const stumblingPoints: StumblingPoint[] = [
  {
    id: 'stumbling-cleanroom',
    category: 'technique',
    title: '無菌調剤（クリーンベンチの使い方）',
    description: '無菌操作の基本が身についていないと、調剤ミスや感染リスクにつながります。',
    difficulty: 'high',
    relatedLearningIds: ['learning-cleanroom-video'],
  },
  {
    id: 'stumbling-pump',
    category: 'phase3',
    title: 'ポンプの取り扱い',
    description: 'シリンジポンプ・輸液ポンプの設定やトラブル対応は現場で必須のスキルです。',
    difficulty: 'high',
    relatedLearningIds: ['learning-pump-video'],
  },
  {
    id: 'stumbling-compatibility',
    category: 'phase3',
    title: '点滴の配合変化・側管投与',
    description: '配合禁忌や側管投与での詰まりは現場でよく起きる問題です。',
    difficulty: 'medium',
    relatedLearningIds: ['learning-compatibility'],
  },
  {
    id: 'stumbling-kasan',
    category: 'phase3',
    title: '加算関係（何が算定できて何がダメか）',
    description: '在宅での加算は複雑で、誤った算定は返戻につながります。',
    difficulty: 'high',
    relatedLearningIds: ['learning-kasan'],
  },
  {
    id: 'stumbling-narcotic',
    category: 'phase4',
    title: '麻薬の換算（フェントスからの切り替え等）',
    description: 'オピオイドの換算ミスは重大な問題につながります。',
    difficulty: 'high',
    relatedLearningIds: ['learning-narcotic'],
  },
  {
    id: 'stumbling-materials',
    category: 'phase3',
    title: '医療材料の処方可否',
    description: '院内処方と院外処方で扱える材料が異なり、判断に迷うケースが多いです。',
    difficulty: 'medium',
    relatedLearningIds: ['learning-materials'],
  },
]

export const checklistItems: ChecklistItem[] = [
  { id: 'check-commitment', title: '本気度を確認する', description: 'どのくらいの規模で在宅を考えているかを確認。', done: false, link: '/onboarding/commitment', linkLabel: '本気度診断へ' },
  { id: 'check-assessment', title: '6軸診断を始める', description: 'いま詰まりやすい点を6軸で確認。', done: false, link: '/onboarding/assessment', linkLabel: '診断へ進む' },
  { id: 'check-position', title: '現在地を確認する', description: 'どの段階にいるかと、次に進む条件を把握。', done: false, link: '/onboarding/result', linkLabel: '現在地を見る' },
  { id: 'check-roadmap', title: 'ロードマップを確認する', description: 'コースに応じた進め方を確認。', done: false, link: '/onboarding/roadmap', linkLabel: 'ロードマップを見る' },
  { id: 'check-week', title: '今週やることを決める', description: '次回会議までに終えるものを1〜2件に絞る。', done: false, link: '/onboarding/tasks', linkLabel: '今週のタスクを見る' },
  { id: 'check-stumbling', title: 'つまずきポイントを確認', description: '現場でよくある問題と対策を把握。', done: false, link: '/onboarding/stumbling', linkLabel: 'つまずきポイントを見る' },
  { id: 'check-support', title: '必要なら伴走依頼を送る', description: 'コメント依頼・添削依頼・困りごとの共有を早めに出す。', done: false, link: '/onboarding/support', linkLabel: '相談する' },
]

export const supportItems: SupportItem[] = [
  { id: 'comment', title: 'コメントをもらう', description: '作成途中の資料でも送ってOK。方向性の確認を先に進めます。', action: '受入条件表にコメント依頼を出す' },
  { id: 'review', title: '添削を依頼する', description: '初回受入フローや説明文の赤入れを依頼できます。', action: '下書きを送って添削依頼を出す' },
  { id: 'trouble', title: '困りごとを共有する', description: '人手・役割分担・患者選定など、詰まりをそのまま共有できます。', action: '困っていることを1件送る' },
  { id: 'setup', title: '立ち上げ支援', description: '現場の運営組み立て、調剤室の模様替え等、伴走が必要な部分の相談。', action: '立ち上げ支援を依頼する' },
]

// フェーズ
export const phaseOrder: PhaseMeta[] = [
  { id: 0, key: 'phase0', label: 'Phase 0', shortLabel: '未着手', title: '在宅導入を検討する', icon: '🔍', summary: '在宅に取り組むかどうかを経営判断する段階です。', gate: 'オーナーが在宅に取り組む方針を決定', milestone: '方針決定', tone: 'info' },
  { id: 1, key: 'phase1', label: 'Phase 1', shortLabel: '方針・体制準備', title: '方針決定と体制準備', icon: '🧭', summary: 'オーナーの意思決定とスタッフへの周知、役割分担を整える段階です。', gate: '方針決定・スタッフ周知・役割分担完了', milestone: '役割分担表', tone: 'info' },
  { id: 2, key: 'phase2', label: 'Phase 2', shortLabel: '受入準備', title: '初回受入の準備', icon: '🧩', summary: '受入条件表、初回フロー、チェックリストを整えて営業に動ける段階です。', gate: '受入条件表・初回フロー作成完了', milestone: '受入条件表 / 初回受入フロー', tone: 'warn' },
  { id: 3, key: 'phase3', label: 'Phase 3', shortLabel: '初回受入', title: '初回患者受入', icon: '🚀', summary: '最初の患者を受け入れ、導入成功を達成する段階です。', gate: '初回受入完了・改善点を回収', milestone: '初回受入レビュー', tone: 'good' },
  { id: 4, key: 'phase4', label: 'Phase 4', shortLabel: '安定運用', title: '安定運用・標準化', icon: '📚', summary: '10-20件程度を安定して運用し、教育・標準化を進める段階です。', gate: '複数スタッフで再現可能な運用', milestone: '教育導線 / 標準資料', tone: 'good' },
  { id: 5, key: 'phase5', label: 'Phase 5', shortLabel: '夜間接続', title: '夜間・緊急対応接続', icon: '🌙', summary: '24時間365日対応を実現し、断らない体制を完成させる段階です。', gate: '患者情報入力体制あり・夜間方針決定', milestone: '夜間支援接続', tone: 'good' },
]

export const comparisonBars = [
  { name: 'この薬局', value: 58, color: '#2f6fed' },
  { name: '先行店舗', value: 76, color: '#00a884' },
  { name: '導入初期店', value: 41, color: '#f08c00' },
]
